apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmq-operator-cr
rules:
- apiGroups: 
  - apps.pl.edu.agh
  resources: 
  - rabbitmqs
  verbs: 
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: 
  - apps.pl.edu.agh
  resources: 
  - rabbitmqs/status
  verbs: 
  - get
  - update
  - patch
- apiGroups: 
  - ""
  resources: 
  - persistentvolumeclaims
  verbs: 
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: 
  - ""
  resources: 
  - pods
  verbs: 
  - get
  - list
  - watch
  - create
  - delete
- apiGroups: 
  - ""
  resources: 
  - configmaps
  verbs: 
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: 
  - apps
  resources: 
  - deployments
  verbs: 
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
