apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-operator-cr
rules:
- apiGroups: 
  - my.domain
  resources: 
  - redis
  verbs: 
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: 
  - my.domain
  resources: 
  - redis/status
  verbs: 
  - get
  - update
  - patch
- apiGroups: 
  - ""
  resources: 
  - persistentvolumeclaims
  verbs: 
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: 
  - ""
  resources: 
  - pods
  verbs: 
  - get
  - list
  - watch
  - create
  - delete
