# permissions for end users to view rabbitmqs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rabbitmq-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rabbitmq
    app.kubernetes.io/part-of: rabbitmq
    app.kubernetes.io/managed-by: kustomize
  name: rabbitmq-viewer-role
rules:
- apiGroups:
  - apps.pl.edu.agh
  resources:
  - rabbitmqs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.pl.edu.agh
  resources:
  - rabbitmqs/status
  verbs:
  - get
