---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - database.pl.edu.agh.operators
  resources:
  - postgres
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.pl.edu.agh.operators
  resources:
  - postgres/finalizers
  verbs:
  - update
- apiGroups:
  - database.pl.edu.agh.operators
  resources:
  - postgres/status
  verbs:
  - get
  - patch
  - update
