apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: game-init-assets-pvc
  namespace: default
  labels:
    app.kubernetes.io/name: game-init
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: game-init-assets-pv
  labels:
    app.kubernetes.io/name: game-init
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /assets
