apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-scripts-pvc
  namespace: default
  labels:
    app.kubernetes.io/name: postgres
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-scripts-pv
  labels:
    type: local
    app.kubernetes.io/name: postgres
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /dbscripts
