apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-scripts-pvc
  namespace: default
  labels:
    app.kubernetes.io/name: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-scripts-pv
  labels:
    type: local
    app.kubernetes.io/name: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /dbscripts
