apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgres.database.pl.edu.agh
spec:
  group: database.pl.edu.agh
  names:
    kind: Postgres
    listKind: PostgresList
    plural: postgres
    singular: postgres
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: Postgres is the Schema for the postgres API
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PostgresSpec defines the desired state of Postgres
            type: object
            properties:
              size:
                description: Number of Postgres instances
                type: integer
              image:
                description: Docker image for the Postgres instance
                type: string
              dbName:
                description: Name of the database
                type: string
              dbUser:
                description: Username for the database
                type: string
              dbPassword:
                description: Password for the database
                type: string
              dbPort:
                description: Port for the database
                type: string
              initScriptsConfigMap:
                description: Name of the ConfigMap with the database init scripts
                type: string
              dataPvcName:
                description: Name of the PVC that will be used for the database data
                type: string
            required:
              - size
              - image
              - dbName
              - dbUser
              - dbPassword
              - dbPort
              - dataPvcName
          status:
            description: PostgresStatus defines the observed state of Postgres
            type: object
            properties:
              nodes:
                description: 'Nodes is the list of Postgres pods'
                type: array
                items:
                  type: string
    subresources:
      status: {}
