apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgres.database.pl.edu.agh
spec:
  group: database.pl.edu.agh
  names:
    kind: Postgres
    listKind: PostgresList
    plural: postgres
    singular: postgres
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              size:
                type: integer
              image:
                type: string
              dbScriptsPath:
                type: string
              dbName:
                type: string
              dbUser:
                type: string
              dbPassword:
                type: string
              dbPort:
                type: string
