apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgreses.kubernetes-operators.pl.edu.agh
spec:
  group: kubernetes-operators.pl.edu.agh
  names:
    kind: Postgres
    listKind: PostgresList
    plural: postgreses
    singular: postgres
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Postgres is the Schema for the postgres API
          type: object
          properties:
            apiVersion:
              description: "APIVersion defines the versioned schema of this representation of an object."
              type: string
            kind:
              description: "Kind is a string value representing the REST resource this object represents."
              type: string
            metadata:
              type: object
            spec:
              description: PostgresSpec defines the desired state of Postgres
              type: object
              properties:
                containers:
                  description: List of containers
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      ports:
                        type: array
                        items:
                          type: object
                          properties:
                            containerPort:
                              type: integer
                      env:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                restartPolicy:
                  description: Restart policy for all containers within the pod
                  type: string
                volumes:
                  description: List of volumes that can be mounted by containers belonging to the pod
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      persistentVolumeClaim:
                        type: object
                        properties:
                          claimName:
                            type: string
              required:
                - containers
                - restartPolicy
                - volumes
            status:
              description: PostgresStatus defines the observed state of Postgres
              type: object
              properties:
                conditions:
                  description: Conditions represent the latest available observations of an object's state
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        description: Type of condition
                        type: string
                      status:
                        description: Status of the condition
                        type: string
                nodes:
                  description: List of Postgres pods
                  type: array
                  items:
                    type: string
      subresources:
        status: {}
