apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgreses.kubernetes-operators.pl.edu.agh
spec:
  group: kubernetes-operators.pl.edu.agh
  names:
    kind: Postgres
    listKind: PostgresList
    plural: postgreses
    singular: postgres
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Postgres is the Schema for the postgreses API
          type: object
          properties:
            apiVersion:
              description: "APIVersion defines the versioned schema of this representation of an object."
              type: string
            kind:
              description: "Kind is a string value representing the REST resource this object represents."
              type: string
            metadata:
              type: object
            spec:
              description: PostgresSpec defines the desired state of Postgres
              type: object
              properties:
                size:
                  description: Size of the Postgres deployment
                  type: integer
                image:
                  description: Docker image for the Postgres instance
                  type: string
                dbName:
                  description: Name of the database
                  type: string
                dbUser:
                  description: Database user
                  type: string
                dbPassword:
                  description: Database password
                  type: string
                dbPort:
                  description: Database port
                  type: string
                initScriptsConfigMap:
                  description: Name of the ConfigMap containing initialization scripts
                  type: string
                dataPvcName:
                  description: Name of the PVC for Postgres data
                  type: string
              required:
                - size
                - image
                - dbName
                - dbUser
                - dbPassword
                - dbPort
                - dataPvcName
            status:
              description: PostgresStatus defines the observed state of Postgres
              type: object
              properties:
                conditions:
                  description: Conditions represent the latest available observations of an object's state
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        description: Type of condition
                        type: string
                      status:
                        description: Status of the condition
                        type: string
                nodes:
                  description: List of Postgres pods
                  type: array
                  items:
                    type: string
      subresources:
        status: {}
