apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqs.apps.pl.edu.agh
spec:
  group: apps.pl.edu.agh
  names:
    kind: RabbitMQ
    listKind: RabbitMQList
    plural: rabbitmqs
    singular: rabbitmq
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: RabbitMQ is the Schema for the rabbitmqs API
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RabbitMQSpec defines the desired state of RabbitMQ
            type: object
            properties:
              containers:
                description: Containers for RabbitMQ instance
                type: array
                items:
                  type: object
                  properties:
                    image:
                      description: Docker image for the container
                      type: string
                    name:
                      description: Name of the container
                      type: string
                    ports:
                      description: Ports to expose from the container
                      type: array
                      items:
                        type: object
                        properties:
                          containerPort:
                            description: Port to expose from the container
                            type: integer
                    volumeMounts:
                      description: Volume mounts for the container
                      type: array
                      items:
                        type: object
                        properties:
                          mountPath:
                            description: Path to mount the volume
                            type: string
                          name:
                            description: Name of the volume
                            type: string
              restartPolicy:
                description: Restart policy for RabbitMQ pods
                type: string
              volumes:
                description: Volumes for RabbitMQ instance
                type: array
                items:
                  type: object
                  properties:
                    name:
                      description: Name of the volume
                      type: string
                    configMap:
                      description: ConfigMap for the volume
                      type: object
                      properties:
                        name:
                          description: Name of the ConfigMap
                          type: string
                        items:
                          description: Items to project from the ConfigMap
                          type: array
                          items:
                            type: object
                            properties:
                              key:
                                description: Key to project
                                type: string
                              path:
                                description: Path to project the key
                                type: string
            required:
              - containers
              - restartPolicy
              - volumes
          status:
            description: RabbitMQStatus defines the observed state of RabbitMQ
            type: object
            properties:
              conditions:
                description: Conditions describe the state of the RabbitMQ instance
                type: array
                items:
                  type: object
                  properties:
                    type:
                      description: Type of the condition
                      type: string
                    status:
                      description: Status of the condition
                      type: string
                    lastUpdateTime:
                      description: Last time the condition was updated
                      type: string
                      format: date-time
                    reason:
                      description: Reason for the condition's last transition
                      type: string
                    message:
                      description: Human-readable message indicating details about last transition
                      type: string
              nodes:
                description: 'Nodes is the list of RabbitMQ pods'
                type: array
                items:
                  type: string
    subresources:
      status: {}
