apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rabbitmq.pl.edu.agh
spec:
  group: apps.pl.edu.agh
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                config:
                  type: string
                plugins:
                  type: string
  names:
    kind: RabbitMQ
    plural: rabbitmqs
    singular: rabbitmq
  scope: Namespaced
