apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqs.apps.pl.edu.agh
spec:
  group: apps.pl.edu.agh
  names:
    kind: RabbitMQ
    listKind: RabbitMQList
    plural: rabbitmqs
    singular: rabbitmq
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: RabbitMQ is the Schema for the rabbitmqs API
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RabbitMQSpec defines the desired state of RabbitMQ
            type: object
            properties:
              image:
                description: Docker image for the RabbitMQ instance
                type: string
              config:
                description: RabbitMQ configuration file
                type: string
              plugins:
                description: Enabled plugins for RabbitMQ
                type: string
              ports:
                description: List of ports to expose from the RabbitMQ container
                type: array
                items:
                  type: object
                  properties:
                    containerPort:
                      description: Port to expose from the container
                      type: integer
            required:
              - image
              - config
              - plugins
          status:
            description: RabbitMQStatus defines the observed state of RabbitMQ
            type: object
            properties:
              nodes:
                description: 'Nodes is the list of RabbitMQ pods'
                type: array
                items:
                  type: string
    subresources:
      status: {}
