apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqs.kubernetes-operators.pl.edu.agh
spec:
  group: kubernetes-operators.pl.edu.agh
  names:
    kind: RabbitMQ
    listKind: RabbitMQList
    plural: rabbitmqs
    singular: rabbitmq
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: RabbitMQ is the Schema for the rabbitmq API
          type: object
          properties:
            apiVersion:
              description: "APIVersion defines the versioned schema of this representation of an object."
              type: string
            kind:
              description: "Kind is a string value representing the REST resource this object represents."
              type: string
            metadata:
              type: object
            spec:
              description: RabbitMQSpec defines the desired state of RabbitMQ
              type: object
              properties:
                containers:
                  description: List of containers for the RabbitMQ pod
                  type: array
                  items:
                    type: object
                    properties:
                      image:
                        description: Docker image for the RabbitMQ instance
                        type: string
                      name:
                        description: Name of the container
                        type: string
                      ports:
                        description: List of ports to expose from the container
                        type: array
                        items:
                          type: object
                          properties:
                            containerPort:
                              description: Port to expose from the container
                              type: integer
                      volumeMounts:
                        description: List of volume mounts for the container
                        type: array
                        items:
                          type: object
                          properties:
                            mountPath:
                              description: Path within the container at which the volume should be mounted
                              type: string
                            name:
                              description: Name of the volume
                              type: string
                restartPolicy:
                  description: Restart policy for all containers within the pod
                  type: string
                volumes:
                  description: List of volumes that can be mounted by containers belonging to the pod
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        description: Volume name
                        type: string
                      configMap:
                        description: Selects a ConfigMap to populate the volume
                        type: object
                        properties:
                          name:
                            description: Name of the referent ConfigMap
                            type: string
                          items:
                            description: List of ConfigMap keys to project into the volume
                            type: array
                            items:
                              type: object
                              properties:
                                key:
                                  description: The key to project
                                  type: string
                                path:
                                  description: The relative path of the file to map the key to
                                  type: string
              required:
                - containers
                - restartPolicy
                - volumes
            status:
              description: RabbitMQStatus defines the observed state of RabbitMQ
              type: object
              properties:
                conditions:
                  description: Conditions represent the latest available observations of an object's state
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        description: Type of condition
                        type: string
                      status:
                        description: Status of the condition
                        type: string
                nodes:
                  description: List of RabbitMQ pods
                  type: array
                  items:
                    type: string
      subresources:
        status: {}
