apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redis.kubernetes-operators.pl.edu.agh
spec:
  group: kubernetes-operators.pl.edu.agh
  names:
    kind: Redis
    listKind: RedisList
    plural: redis
    singular: redis
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Redis is the Schema for the redis API
          type: object
          properties:
            apiVersion:
              description: "APIVersion defines the versioned schema of this representation of an object."
              type: string
            kind:
              description: "Kind is a string value representing the REST resource this object represents."
              type: string
            metadata:
              type: object
            spec:
              description: RedisSpec defines the desired state of Redis
              type: object
              properties:
                size:
                  description: Size of the Redis deployment
                  type: integer
                image:
                  description: Docker image for the Redis instance
                  type: string
                port:
                  description: Redis port
                  type: integer
                dataPvcName:
                  description: Name of the PVC for Redis data
                  type: string
              required:
                - size
                - image
                - port
                - dataPvcName
            status:
              description: RedisStatus defines the observed state of Redis
              type: object
              properties:
                conditions:
                  description: Conditions represent the latest available observations of an object's state
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        description: Type of condition
                        type: string
                      status:
                        description: Status of the condition
                        type: string
                nodes:
                  description: List of Redis pods
                  type: array
                  items:
                    type: string
      subresources:
        status: {}
