apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  ports:
    - protocol: TCP
      port: 2138
      targetPort: 2138
  selector:
    app.kubernetes.io/name: chat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  namespace: default
  labels:
    app.kubernetes.io/name: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chat
  template:
    metadata: 
      labels:
        app.kubernetes.io/name: chat
    spec:
      containers:
        - image: michwoj01/ecsb:chat
          name: chat
          ports:
            - containerPort: 2138
      restartPolicy: Always
