apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  ports:
    - protocol: TCP
      port: 2138
      targetPort: 2138
  selector:
    app.kubernetes.io/name: chat
---
apiVersion: v1
kind: Pod
metadata:
  name: chat-pod
  labels:
    app.kubernetes.io/name: chat
spec:
  containers:
    - image: michwoj01/ecsb:chat
      name: chat
      ports:
        - containerPort: 2138
  restartPolicy: OnFailure
