apiVersion: v1
kind: Pod
metadata:
  name: game-engine-pod
  labels:
    app.kubernetes.io/name: game-engine
spec:
  containers:
    - image: michwoj01/ecsb:game-engine
      name: game-engine
  restartPolicy: OnFailure
