apiVersion: v1
kind: Service
metadata:
  name: game-init
spec:
  ports:
    - protocol: TCP
      port: 2136
      targetPort: 2136
  selector:
    app.kubernetes.io/name: game-init
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-init
  namespace: default
  labels:
    app.kubernetes.io/name: game-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: game-init
  template:
    metadata:
      labels:
        app.kubernetes.io/name: game-init
    spec:
      containers:
        - image: michwoj01/ecsb:game-init
          name: game-init
          ports:
            - containerPort: 2136
          volumeMounts:
            - mountPath: /assets
              name: game-init-assets
      restartPolicy: Always
      volumes:
        - name: game-init-assets
          persistentVolumeClaim:
            claimName: game-init-assets-pvc
