apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-engine
  namespace: default
  labels:
    app.kubernetes.io/name: game-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: game-engine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: game-engine
    spec:
      containers:
        - image: michwoj01/ecsb:game-engine
          name: game-engine
      restartPolicy: Always
