apiVersion: v1
kind: Service
metadata:
  name: game-init
spec:
  ports:
    - protocol: TCP
      port: 2136
      targetPort: 2136
  selector:
    app.kubernetes.io/name: game-init
---
apiVersion: v1
kind: Pod
metadata:
  name: game-init
  labels:
    app.kubernetes.io/name: game-init
spec:
  containers:
    - image: michwoj01/ecsb:game-init
      name: game-init
      ports:
        - containerPort: 2136
  restartPolicy: OnFailure
