apiVersion: v1
kind: Service
metadata:
  name: moving
spec:
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  selector:
    app.kubernetes.io/name: moving
---
apiVersion: v1
kind: Pod
metadata:
  name: moving
  labels:
    app.kubernetes.io/name: moving
spec:
  containers:
    - image: michwoj01/ecsb:moving
      name: moving
      ports:
        - containerPort: 8085
  restartPolicy: OnFailure
