apiVersion: v1
kind: Service
metadata:
  name: moving
spec:
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  selector:
    app.kubernetes.io/name: moving
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moving
  namespace: default
  labels:
    app.kubernetes.io/name: moving
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: moving
  template:
    metadata: 
      labels:
        app.kubernetes.io/name: moving
    spec:
      containers:
        - image: michwoj01/ecsb:moving
          name: moving
          ports:
            - containerPort: 8085
      restartPolicy: Always
