apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  containers:
    - image: postgres:15.3
      name: postgres
      env:
        - name: POSTGRES_DB
          value: "mydb"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
      ports:
        - containerPort: 5432
      resources: { }
      volumeMounts:
        # TODO: move to persistent storage 
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
        # TODO: move to dockerfile 
        - mountPath: /docker-entrypoint-initdb.d/
          name: postgres-scripts
  restartPolicy: OnFailure
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: postgres-data-claim
    - name: postgres-scripts
      persistentVolumeClaim:
        claimName: postgres-scripts-claim
