apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-operator
  template:
    metadata:
      labels:
        app: postgres-operator
    spec:
      serviceAccountName: postgres-operator-sa
      containers:
      - name: operator
        image: matipl01/kubernetes-operators:v0.1.22
        ports:
        - containerPort: 8080
        args:
        - "--zap-log-level=debug"
        - "--zap-stacktrace-level=info"
        - "--zap-encoder=console"
---
apiVersion: database.pl.edu.agh/v1
kind: Postgres
metadata:
  name: postgres
  namespace: default
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/part-of: kubernetes-operators
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-operators
spec:
  size: 1
  image: postgres:15.3
  dbName: mydb
  dbUser: postgres
  dbPassword: postgres
  dbPort: "5432"
  scriptsPvcName: "postgres-scripts-pvc"
  dataPvcName: "postgres-data-pvc"
