apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - name: "postgres"
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-operator
    spec:
      serviceAccountName: kubernetes-operators-sa
      containers:
        - name: operator
          image: matipl01/ecsb-postgres-operator:v1.0.6
          ports:
            - name: "postgres"
              containerPort: 5432
          args:
            - "--zap-log-level=debug"
            - "--zap-stacktrace-level=info"
            - "--zap-encoder=console"
---
apiVersion: kubernetes-operators.pl.edu.agh/v1
kind: Postgres
metadata:
  name: postgres
  namespace: default
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/part-of: kubernetes-operators
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-operators
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:13
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_PORT
          value: "5432"
  restartPolicy: Always
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: postgres-pvc
