apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-operator
    spec:
      serviceAccountName: kubernetes-operators-sa
      containers:
        - name: operator
          image: matipl01/ecsb-postgres-operator:v1.0.0
          ports:
            - containerPort: 5432
          args:
            - "--zap-log-level=debug"
            - "--zap-stacktrace-level=info"
            - "--zap-encoder=console"
---
apiVersion: database.pl.edu.agh/v1
kind: Postgres
metadata:
  name: postgres
  namespace: default
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/part-of: kubernetes-operators
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-operators
    app: postgres
spec:
  size: 1
  image: postgres:15.3
  dbName: mydb
  dbUser: postgres
  dbPassword: postgres
  dbPort: "5432"
  dataPvcName: "postgres-data-pvc"
  initScriptsConfigMap: "postgres-init-scripts"
