apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgres
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  containers:
    - image: postgres:15.3
      name: postgres
      env:
        - name: POSTGRES_DB
          value: "mydb"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
      ports:
        - containerPort: 5432
      volumeMounts:
        # TODO: move to persistent storage 
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
        # TODO: move to persistent storage and provide scripts inside cluster
        - mountPath: /docker-entrypoint-initdb.d/
          name: postgres-scripts
  restartPolicy: OnFailure
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: postgres-data-claim
    - name: postgres-scripts
      persistentVolumeClaim:
        claimName: postgres-scripts-claim
