apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: "management"
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: "connections"
      protocol: TCP
      port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq-operator
    spec:
      serviceAccountName: kubernetes-operators-sa
      containers:
        - name: operator
          image: matipl01/ecsb-rabbitmq-operator:v1.0.4
          ports:
            - containerPort: 5672
          args:
            - "--zap-log-level=debug"
            - "--zap-stacktrace-level=info"
            - "--zap-encoder=console"
---
apiVersion: kubernetes-operators.pl.edu.agh/v1
kind: RabbitMQ
metadata:
  name: rabbitmq
  namespace: default
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/part-of: kubernetes-operators
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-operators
    app: rabbitmq
spec:
  containers:
    - image: rabbitmq:3.12-management
      name: rabbitmq
      ports:
        - containerPort: 15672
        - containerPort: 5672
      volumeMounts:
        - mountPath: /etc/rabbitmq/
          name: rabbitmq
  restartPolicy: Always
  volumes:
    - name: rabbitmq
      configMap:
        name: rabbitmq-config
        items:
          - key: rabbitmq-conf
            path: rabbitmq.conf
          - key: enabled-plugins
            path: enabled_plugins
