apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  ports:
    - name: "management"
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: "connections"
      protocol: TCP
      port: 5672
      targetPort: 5672
  selector:
    app.kubernetes.io/name: rabbitmq
---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
spec:
  containers:
    - image: rabbitmq:3.12-management
      name: rabbitmq
      ports:
        - containerPort: 15672
        - containerPort: 5672
      volumeMounts:
        - mountPath: /etc/rabbitmq/
          name: rabbitmq
  restartPolicy: Always
  volumes:
    - name: rabbitmq
      configMap:
        name: rabbitmq-config
        items:
        - key: rabbitmq-conf
          path: rabbitmq.conf
        - key: enabled-plugins
          path: enabled_plugins