apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
spec:
  containers:
    - image: rabbitmq:3.12-management
      name: rabbitmq
      ports:
        - containerPort: 15672
        - containerPort: 5672
      resources: {}
      volumeMounts:
        - mountPath: /etc/rabbitmq/
          name: rabbitmq
  restartPolicy: Always
  volumes:
    - name: rabbitmq
      configMap:
        name: rabbitmq
        items:
        - key: rabbitmq-conf
          path: rabbitmq.conf
        - key: enabled-plugins
          path: enabled_plugins
status: {}
