apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: default
spec:
  ports:
    - name: "management"
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: "connections"
      protocol: TCP
      port: 5672
      targetPort: 5672
  selector:
    app.kubernetes.io/name: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-operator
  template:
    metadata:
      labels:
        app: rabbitmq-operator
    spec:
      serviceAccountName: rabbitmq-operator-sa
      containers:
      - name: operator
        image: matipl01/ecsb-rabbitmq-operator:v0.1.0
        ports:
        - containerPort: 8080
        args:
        - "--zap-log-level=debug"
        - "--zap-stacktrace-level=info"
        - "--zap-encoder=console"
---
apiVersion: apps.pl.edu.agh/v1
kind: RabbitMQ
metadata:
  name: rabbitmq
  namespace: default
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/part-of: kubernetes-operators
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-operators
spec:
  image: rabbitmq:3.12-management
  config: |
    vm_memory_high_watermark.relative = 0.4
    vm_memory_calculation_strategy = rss
  plugins: "[rabbitmq_management,rabbitmq_sharding]."
  ports:
    - containerPort: 15672
    - containerPort: 5672
