apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: "management"
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: "connections"
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-operator
    spec:
      serviceAccountName: redis-operator-sa
      containers:
        - name: operator
          image: domkvv/redis-operator:v1.0.0
          ports:
            - name: "management"
              protocol: TCP
              port: 8001
              targetPort: 8001
            - name: "connections"
              protocol: TCP
              port: 6379
              targetPort: 6379
          args:
            - "--zap-log-level=debug"
            - "--zap-stacktrace-level=info"
            - "--zap-encoder=console"
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  containers:
    - image: redis/redis-stack
      name: redis
      ports:
        - containerPort: 8001
        - containerPort: 6379
      volumeMounts:
        - mountPath: /redis_data
          name: redis-cache
  restartPolicy: OnFailure
  volumes:
    - name: redis-cache
      persistentVolumeClaim:
        claimName: redis-cache-pvc
