apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: "management"
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: "connections"
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: redis
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  containers:
    - image: redis/redis-stack
      name: redis
      ports:
        - containerPort: 8001
        - containerPort: 6379
      volumeMounts:
        # TODO: move to persistent storage
        - mountPath: /redis_data
          name: redis-cache
  restartPolicy: OnFailure
  volumes:
    - name: redis-cache
      persistentVolumeClaim:
        claimName: redis-cache-claim
