apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  containers:
    - image: redis/redis-stack
      name: redis
      ports:
        - containerPort: 8001
        - containerPort: 6379
      resources: {}
      volumeMounts:
        # TODO: move to persistent storage (?)
        - mountPath: /redis_data
          name: redis-cache
  restartPolicy: OnFailure
  volumes:
    - name: redis-cache
      persistentVolumeClaim:
        claimName: redis-cache-claim
status: {}
