apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: "management"
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: "connections"
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-operator
    spec:
      serviceAccountName: kubernetes-operators-sa
      containers:
        - name: operator
          image: matipl01/ecsb-redis-operator:v0.1.0
          ports:
            - name: "management"
              containerPort: 8001
            - name: "connections"
              containerPort: 6379
          args:
            - "--zap-log-level=debug"
            - "--zap-stacktrace-level=info"
            - "--zap-encoder=console"
---
apiVersion: my.domain/v1
kind: Redis
metadata:
  name: redis
  namespace: default
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/part-of: kubernetes-operators
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-operators
    app: redis
spec:
  size: 1
  image: redis/redis-stack
  port: 6379
  dataPvcName: "redis-cache-pvc"
