apiVersion: apps/v1
kind: Deployment
metadata:
  name: timer
  namespace: default
  labels:
    app.kubernetes.io/name: timer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: timer
  template:
    metadata: 
      labels:
        app.kubernetes.io/name: timer
    spec:
      containers:
        - image: michwoj01/ecsb:timer
          name: timer
      restartPolicy: Always
